fiscal year feature
Daanphe/nepali_calendar pull request #4
Opened 2022-05-26 11:37 UTC by sangamsth

2022-05-27 05:12 UTC, Sagar535 approved these changes

2022-05-27 05:45 UTC, sarojkh requested changes
@sangamsth Nice job! 

I would like to request some more changes, which deviate from the original issue ticket. 

1. NepaliCalendar::AdCalendar should have its own `get_fiscal_year(ad_date)`
2. NepaliCalendar::BsCalendar should have its own `get_fiscal_year(bs_date)`
3. NepaliCalendar::AdCalendar should **also**  have its own `current_fiscal_year`
4. Introduce FiscalYear as a class. I was thinking the following structure for it. 
```ruby
class NepaliCalendar::FiscalYear

# These are string representation of year like '77', '78'
attr_accessor :start_year, :end_year

def initialize(start_year, end_year)
# TODO
end

# Should return_the_date in bs
def beginning_of_year
# TODO
end

# Should return the date in bs
def end_of_year
# TODO
end

# Should return the '7879' form of string.
def to_s
# TODO
end
```

2022-05-27 05:45 UTC, sarojkh commented on spec/nepali_calendar_spec.rb
> +    end
We want to check the border jump here. The existing test should also be backed by checking the day before and the expected fiscal year. Place it inside this `it` block/example itself.

2022-05-27 05:45 UTC, sarojkh commented on spec/nepali_calendar_spec.rb
> +    end
Same as above. Gotta check the border jump.

2022-05-31 04:53 UTC, sarojkh commented
Closing in favor of #5

2022-05-31 04:54 UTC, closed without merging