Fiscal year
Daanphe/nepali_calendar pull request #7
Opened 2022-06-13 05:59 UTC by sangamsth

2022-06-20 07:45 UTC, sarojkh requested changes

2022-06-20 07:45 UTC, sarojkh commented on README.md
> +##### Rails 6.1.0+
Change all 'sh to'  'ruby', such that the code formatting is ruby based(and easy to scan too, maybe?)

See the following as comparison - sh vs ruby, respectively.
![Screen Shot 2022-06-20 at 13 23 35](https://user-images.githubusercontent.com/7038624/174550127-f406e372-aff0-4006-9278-3cb54aece0d8.png)

2022-06-20 07:45 UTC, sarojkh commented on lib/exceptions/exceptions.rb
> +    NOCODE = 0o00
Any reason for this change?

2022-06-20 07:45 UTC, sarojkh commented on lib/nepali_calendar/ad_calendar.rb
> +          formatted_date.end_of_week
The indentations on multiple methods in this file looks very very off.

2022-06-20 08:16 UTC, sangamsth commented on lib/exceptions/exceptions.rb
> +    NOCODE = 0o00
this could be a typo mistake

2022-06-20 08:48 UTC, sarojkh requested changes
Lets fix the following as well: 
![Screen Shot 2022-06-20 at 14 30 44](https://user-images.githubusercontent.com/7038624/174562979-a8c7c7d3-e346-425f-89b8-856a61ef6a8f.png)
![Screen Shot 2022-06-20 at 14 30 21](https://user-images.githubusercontent.com/7038624/174563003-2f950d7f-7235-40b1-a24b-710ce7e08e4f.png)
![Screen Shot 2022-06-20 at 14 30 10](https://user-images.githubusercontent.com/7038624/174563008-5e37cb9e-692f-4619-a102-6f2e11885532.png)
![Screen Shot 2022-06-20 at 14 29 54](https://user-images.githubusercontent.com/7038624/174563014-48aaebb0-e49d-4ee4-b7d8-386767b4a4bd.png)
![Screen Shot 2022-06-20 at 14 29 46](https://user-images.githubusercontent.com/7038624/174563017-fae350aa-af0e-4723-8ef5-6494dc5c2614.png)
![Screen Shot 2022-06-20 at 14 29 40](https://user-images.githubusercontent.com/7038624/174563021-2ec1f150-9aa0-460c-b896-dc60c034260c.png)
![Screen Shot 2022-06-20 at 14 29 23](https://user-images.githubusercontent.com/7038624/174563024-f39f0642-b66c-4de6-89ae-f0772fd1f1cd.png)
![Screen Shot 2022-06-20 at 14 29 14](https://user-images.githubusercontent.com/7038624/174563028-ba1c9c0a-e9ed-4853-baef-0744dc10c94e.png)
![Screen Shot 2022-06-20 at 14 29 06](https://user-images.githubusercontent.com/7038624/174563031-8aa855a2-a5ab-4fa0-954b-f5e04f4dd959.png)
![Screen Shot 2022-06-20 at 14 28 57](https://user-images.githubusercontent.com/7038624/174563033-f9a174fc-aeff-47c8-ae0f-be9b316bb0c8.png)
![Screen Shot 2022-06-20 at 14 28 50](https://user-images.githubusercontent.com/7038624/174563036-06836727-242e-4c42-adc0-68f7840f8de5.png)
![Screen Shot 2022-06-20 at 14 28 44](https://user-images.githubusercontent.com/7038624/174563037-d90279fd-1211-4601-a504-0f21c357d9a4.png)
![Screen Shot 2022-06-20 at 14 27 55](https://user-images.githubusercontent.com/7038624/174563041-ea5510ad-c1e8-4754-b7bd-9013c9e88bf6.png)
![Screen Shot 2022-06-20 at 14 27 48](https://user-images.githubusercontent.com/7038624/174563043-faea7fdf-5f6e-4385-8840-85f5159431d4.png)
![Screen Shot 2022-06-20 at 14 27 42](https://user-images.githubusercontent.com/7038624/174563050-c8713c8d-51d0-4d77-982f-11e32e5ddc8a.png)
![Screen Shot 2022-06-20 at 14 27 36](https://user-images.githubusercontent.com/7038624/174563054-35eea9c8-8f73-4b87-9e38-b3ea1c7e7ad0.png)
![Screen Shot 2022-06-20 at 14 27 26](https://user-images.githubusercontent.com/7038624/174563057-994f59ff-ff60-4933-a64f-ef238f206be6.png)
![Screen Shot 2022-06-20 at 14 27 17](https://user-images.githubusercontent.com/7038624/174563062-07d2a2a6-c7eb-42b2-bac6-f760bf9b6f52.png)
![Screen Shot 2022-06-20 at 14 27 10](https://user-images.githubusercontent.com/7038624/174563065-3258fc14-3874-4d20-bc5a-beccd587853f.png)
![Screen Shot 2022-06-20 at 14 26 59](https://user-images.githubusercontent.com/7038624/174563066-4824b39b-ccad-4167-a0c3-75251ac596e4.png)
![Screen Shot 2022-06-20 at 14 26 47](https://user-images.githubusercontent.com/7038624/174563069-bde2f418-fe07-4205-8423-a93e109dfcdb.png)
![Screen Shot 2022-06-20 at 14 26 37](https://user-images.githubusercontent.com/7038624/174563072-c151cd87-f5b3-4091-9f36-86e45ee6a790.png)
![Screen Shot 2022-06-20 at 14 26 10](https://user-images.githubusercontent.com/7038624/174563078-4368c48f-f98a-4303-b930-b7c2e7ad5b54.png)
![Screen Shot 2022-06-20 at 14 26 04](https://user-images.githubusercontent.com/7038624/174563083-e6a1d1d5-3a8f-4511-b957-a8d9c78010b7.png)
![Screen Shot 2022-06-20 at 14 25 56](https://user-images.githubusercontent.com/7038624/174563084-86db1175-f435-4b32-9e75-a27f7c2f5a91.png)
![Screen Shot 2022-06-20 at 14 25 47](https://user-images.githubusercontent.com/7038624/174563087-efbc9a70-7ac5-45dc-87dd-03f9353663ef.png)
![Screen Shot 2022-06-20 at 14 25 28](https://user-images.githubusercontent.com/7038624/174563088-165b4b71-025a-4d0f-a227-53700e196f66.png)

2022-06-20 12:02 UTC, sarojkh requested changes
Can no longer run specs. 
![Screen Shot 2022-06-20 at 17 47 29](https://user-images.githubusercontent.com/7038624/174597421-bce7f1ac-4a1a-4c89-9867-ff1418821d6d.png)

2022-06-20 12:02 UTC, sarojkh commented on lib/exceptions/exceptions.rb
> +    NOCODE = 0o00
This is not an octal number. Not every cop violation in rubocop is valid; this is one of those instances.

2022-06-21 06:11 UTC, sarojkh requested changes

2022-06-21 06:11 UTC, sarojkh commented on nepali_calendar.gemspec
> +$LOAD_PATH.unshift File.expand_path('../lib', __dir__)
Lets revert this hunk

2022-06-21 07:59 UTC, merged